// Détection AUTOMATIQUE des compétitions (logique PURE, testable, sans IO).
//
// Pourquoi : jusqu'ici, une activité ne comptait comme course que si l'athlète avait
// coché « course » sur Strava (`is_race` / `workout_type = 1`). Or presque personne ne
// le fait — un athlète arrivé avec quatre ans d'historique et 427 sorties avait ZÉRO
// course étiquetée, alors que son historique contenait un marathon et deux semis.
// Résultat : le moteur n'avait aucun ancrage et retombait sur des allures génériques.
// Demander à l'utilisateur d'étiqueter, c'est lui demander de faire le travail de
// l'algorithme. On détecte.
//
// PRÉCISION AVANT RAPPEL. Une fausse course entre dans l'ancrage et y reste : elle
// déplace durablement toutes les projections. Une course manquée ne fait que priver le
// moteur d'un point. Les seuils sont donc calés pour ne quasiment jamais se tromper,
// quitte à n'attraper qu'une partie des courses.
//
// ── Calibration (mesurée, pas devinée) ───────────────────────────────────────────
// Sur les compétitions déjà étiquetées de la base, confrontées à tout le reste :
//
//   signal                    courses étiquetées     autres sorties
//   temps d'arrêt (médiane)         0,2 %          0,5 – 0,9 % (p90 : 5 – 7 %)
//   FC (centile personnel)          haut            réparti
//   titre auto Strava               2 / 18          291 occurrences
//
// Le %FCmax ABSOLU a été écarté : `fc_max` est saisi à la main et se révèle faux chez
// certains athlètes (des footings à 88 % de FCmax). On utilise donc le rang de la FC
// dans la PROPRE distribution de l'athlète — insensible à une FCmax mal renseignée.

/** Part maximale de temps d'arrêt (%) — une course ne s'arrête pas. */
export const MAX_STOP_RATIO_PCT = 3
/** Centile minimal de FC dans la distribution personnelle de l'athlète. */
export const MIN_HR_PERCENTILE = 0.85
/** Distance minimale considérée (m). */
export const MIN_DISTANCE_M = 3000

/**
 * Titres AUTOMATIQUES de Strava. Un athlète qui court un dossard renomme son activité ;
 * un titre par défaut est donc un signal négatif fort (2 sur 18 seulement chez les
 * courses étiquetées, contre 291 occurrences ailleurs).
 */
const AUTO_TITLE = [
  /^(morning|afternoon|evening|lunch|night)\s+(run|trail\s*run|walk|hike)\s*$/,
  /^course\s+[àa]\s+pied\s*(le\s+matin|le\s+midi|le\s+soir|matinale|nocturne|dans\s+l.apr[èe]s-midi|l.apr[èe]s-midi)?\s*$/,
  /^trail\s*(run)?\s*(le\s+matin|le\s+midi|le\s+soir|en\s+soir[ée]e|nocturne|dans\s+l.apr[èe]s-midi)?\s*$/,
  /^sortie\s+(à\s+pied|course|longue)?\s*(le\s+matin|le\s+midi|le\s+soir|dans\s+l.apr[èe]s-midi)?\s*$/,
]

/** Motifs de SÉANCE : structure d'entraînement dans le nom → ce n'est pas une course. */
const SESSION_PATTERNS = [
  /[0-9]+\s*[x*]\s*[0-9]/, // 10x400, 4x2km
  /allure/, /fractionn/, /tempo/, /\bvma\b/, /seuil/, /\bef\b/,
  /footing/, /chauffement/, /crassage/, /r[ée]cup/,
  /rando/, /sortie\s+longue/, /jardinage/, /\breco\b/,
  /\btest\b/, /entra[îi]n/,
]

/** Motifs de COURSE : nom d'événement ou classement annoncé. */
const RACE_PATTERNS = [
  /marathon/, /semi/, /corrida/, /foul[ée]e/, /ekiden/,
  /challenge/, /championnat/, /\bcross\b/, /course\s+de\s+/,
  /[0-9]{1,3}\s*\/\s*[0-9]{2,4}/,          // « 42/389 »
  /[0-9]{1,3}\s*(e|er|[èe]me)\s+(au\s+g[ée]n[ée]ral|scratch)/, // « 29e au général »
]

const RUN_SPORTS = new Set(['run', 'trailrun', 'trail run', 'running', 'virtualrun'])

export interface RaceDetectionInput {
  name?: string | null
  sportType?: string | null
  type?: string | null
  distanceM?: number | null
  movingTimeS?: number | null
  elapsedTimeS?: number | null
  /**
   * Rang de la FC moyenne dans la distribution PERSONNELLE de l'athlète (0..1).
   * Absent → le critère d'intensité ne peut pas être vérifié, donc pas de détection
   * (on ne détecte jamais sur le seul nom : « Marathon » peut être un footing).
   */
  hrPercentile?: number | null
}

export interface RaceDetectionResult {
  /** Vrai si l'activité peut être traitée comme une compétition sans étiquetage. */
  detected: boolean
  /** Codes machine expliquant la décision (sûrs à journaliser, sans données perso). */
  reasons: string[]
}

function norm(s?: string | null): string {
  return (s ?? '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').trim()
}

/** Vrai si le titre est celui généré par défaut par Strava (jamais renommé). */
export function hasAutoGeneratedTitle(name?: string | null): boolean {
  const n = norm(name)
  if (!n) return true
  return AUTO_TITLE.some((re) => re.test(n))
}

/**
 * Détecte une compétition sans s'appuyer sur l'étiquetage Strava.
 *
 * Exige TOUS les critères : sport de course, distance suffisante, titre personnalisé,
 * nom d'événement reconnaissable, aucun motif de séance, temps d'arrêt faible, et
 * intensité dans le haut de la distribution personnelle. Le cumul est volontairement
 * strict — cf. en-tête, précision avant rappel.
 */
export function detectRace(input: RaceDetectionInput): RaceDetectionResult {
  const reasons: string[] = []
  const sport = norm(input.sportType) || norm(input.type)
  if (!RUN_SPORTS.has(sport)) return { detected: false, reasons: ['sport_not_run'] }

  const dist = input.distanceM
  if (typeof dist !== 'number' || !(dist >= MIN_DISTANCE_M)) {
    return { detected: false, reasons: ['distance_too_short'] }
  }

  const moving = input.movingTimeS
  if (typeof moving !== 'number' || moving <= 0) return { detected: false, reasons: ['no_real_time'] }

  const name = norm(input.name)
  if (hasAutoGeneratedTitle(input.name)) return { detected: false, reasons: ['auto_generated_title'] }
  if (SESSION_PATTERNS.some((re) => re.test(name))) return { detected: false, reasons: ['looks_like_workout'] }
  if (!RACE_PATTERNS.some((re) => re.test(name))) return { detected: false, reasons: ['no_race_name_signal'] }
  reasons.push('race_name_signal')

  // Temps d'arrêt : une course ne s'arrête pas (médiane mesurée 0,2 %).
  const elapsed = input.elapsedTimeS
  if (typeof elapsed === 'number' && elapsed > 0) {
    const stopPct = ((elapsed - moving) / moving) * 100
    if (stopPct > MAX_STOP_RATIO_PCT) return { detected: false, reasons: ['too_many_stops'] }
    reasons.push('low_stop_ratio')
  }

  // Intensité RELATIVE à l'athlète (immunisée contre une FCmax mal saisie).
  const pct = input.hrPercentile
  if (typeof pct !== 'number' || !Number.isFinite(pct)) {
    return { detected: false, reasons: [...reasons, 'no_intensity_signal'] }
  }
  if (pct < MIN_HR_PERCENTILE) return { detected: false, reasons: [...reasons, 'intensity_too_low'] }
  reasons.push('personal_intensity_high')

  return { detected: true, reasons }
}

export interface HrSample {
  averageHeartrate?: number | null
}

/**
 * Rang (0..1) de chaque FC moyenne dans la distribution de l'athlète. Renvoie une
 * fonction de consultation — le classement n'est calculé qu'une fois.
 *
 * Le rang est celui de la FC parmi les activités de course à pied EXPLOITABLES de
 * l'athlète : c'est ce qui rend le critère d'intensité indépendant d'une `fc_max`
 * saisie à la main, souvent fausse.
 */
export function buildHrPercentileLookup(samples: HrSample[]): (hr?: number | null) => number | null {
  const values = samples
    .map((s) => s.averageHeartrate)
    .filter((h): h is number => typeof h === 'number' && Number.isFinite(h) && h > 0)
    .sort((a, b) => a - b)
  if (values.length < 10) return () => null // trop peu d'historique pour un rang fiable
  return (hr) => {
    if (typeof hr !== 'number' || !Number.isFinite(hr) || hr <= 0) return null
    // Part des valeurs STRICTEMENT inférieures → rang dans [0,1).
    let lo = 0
    let hi = values.length
    while (lo < hi) {
      const mid = (lo + hi) >> 1
      if (values[mid] < hr) lo = mid + 1
      else hi = mid
    }
    return values.length > 1 ? lo / (values.length - 1) : 0
  }
}
