import { describe, it, expect } from 'vitest'
import {
  detectRace,
  hasAutoGeneratedTitle,
  buildHrPercentileLookup,
  MIN_HR_PERCENTILE,
} from '../src/lib/raceDetection'
import { detectRace as mobileDetect } from '../mobile/src/lib/raceDetection'

// Détection AUTOMATIQUE des compétitions. Presque personne ne coche « course » sur
// Strava : un athlète arrivé avec 4 ans d'historique et 427 sorties avait ZÉRO course
// étiquetée, alors que son historique contenait un marathon et deux semis. Sans
// détection, le moteur n'a aucun ancrage.
//
// PRÉCISION AVANT RAPPEL : une fausse course entre dans l'ancrage et y déplace
// durablement toutes les projections ; une course manquée ne fait que priver le moteur
// d'un point. Les cas ci-dessous sont TIRÉS DES DONNÉES RÉELLES.

const base = {
  sportType: 'Run',
  distanceM: 21100,
  movingTimeS: 5248,
  elapsedTimeS: 5274, // 0,5 % d'arrêt
  hrPercentile: 1.0,
}

describe('detectRace — vraies courses (doivent être détectées)', () => {
  it('1. « Marathon de colmar 2025 » — 41,9 km, 1,1 % d’arrêt, FC au 97e centile', () => {
    const r = detectRace({ ...base, name: 'Marathon de colmar 2025', distanceM: 41900, movingTimeS: 11294, elapsedTimeS: 11418, hrPercentile: 0.97 })
    expect(r.detected).toBe(true)
    expect(r.reasons).toContain('race_name_signal')
    expect(r.reasons).toContain('personal_intensity_high')
  })

  it('2. « Semi marathon de Mulhouse »', () => {
    expect(detectRace({ ...base, name: 'Semi marathon de Mulhouse' }).detected).toBe(true)
  })

  it('3. « Trail du muguet. 42/389 funny fun » — classement dans le nom', () => {
    const r = detectRace({ ...base, sportType: 'TrailRun', name: 'Trail du muguet. 42/389 funny fun', distanceM: 11594, movingTimeS: 4185, elapsedTimeS: 4188, hrPercentile: 0.96 })
    expect(r.detected).toBe(true)
  })

  it('4. « Trail des collines 29e au général » — placement annoncé', () => {
    const r = detectRace({ ...base, sportType: 'TrailRun', name: 'Trail des collines 29e au général, vraiment content', distanceM: 22663, movingTimeS: 7196, elapsedTimeS: 7209, hrPercentile: 0.93 })
    expect(r.detected).toBe(true)
  })
})

describe('detectRace — pièges observés (ne doivent PAS être détectés)', () => {
  it('5. « Trail dans l’après-midi » — titre AUTOMATIQUE Strava', () => {
    // Le seul vrai faux positif de la calibration : attrapé par un motif « trail d… »
    // trop laxiste. Le titre auto le rejette proprement.
    const r = detectRace({ ...base, sportType: 'TrailRun', name: "Trail dans l'après-midi" })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('auto_generated_title')
  })

  it('6. titres auto français et anglais rejetés', () => {
    for (const n of ['Course à pied le matin', 'Morning Run', 'Afternoon Trail Run', 'Trail le matin', 'Lunch Run', 'Course à pied matinale']) {
      expect(hasAutoGeneratedTitle(n), n).toBe(true)
      expect(detectRace({ ...base, name: n }).detected, n).toBe(false)
    }
  })

  it('7. séances structurées rejetées malgré une intensité de course', () => {
    for (const n of ['4x2km allure semi', 'VMA 10x400', '3x5 min tempo', 'Séance test semi', 'Fartlek 10km', 'Test de forme COROS']) {
      expect(detectRace({ ...base, name: n }).detected, n).toBe(false)
    }
  })

  it('8. sortie à titre personnalisé mais sans nom d’événement → non détectée', () => {
    // On ne confirme jamais sur la seule intensité : une sortie dominicale soutenue
    // ressemble physiologiquement à une course.
    const r = detectRace({ ...base, name: 'Il pleut comme vache qui pisse 👀' })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('no_race_name_signal')
  })

  it('9. trop d’arrêts → rejetée (une course ne s’arrête pas)', () => {
    const r = detectRace({ ...base, name: 'Marathon de Colmar', elapsedTimeS: 5248 * 1.12 })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('too_many_stops')
  })

  it('10. intensité trop basse → rejetée (« rando course » nommée comme une course)', () => {
    const r = detectRace({ ...base, name: 'Marathon de Colmar', hrPercentile: 0.4 })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('intensity_too_low')
  })

  it('11. sans signal d’intensité → JAMAIS détectée', () => {
    // Un nom seul ne suffit pas : « Marathon » peut être un footing sur le parcours.
    const r = detectRace({ ...base, name: 'Marathon de Colmar', hrPercentile: null })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('no_intensity_signal')
  })

  it('12. vélo et distances courtes écartés', () => {
    expect(detectRace({ ...base, sportType: 'Ride', name: 'Marathon de Colmar' }).detected).toBe(false)
    expect(detectRace({ ...base, name: 'Corrida de Noël', distanceM: 2000 }).detected).toBe(false)
  })
})

describe('buildHrPercentileLookup', () => {
  it('13. historique trop mince → aucun rang (donc aucune détection)', () => {
    const lookup = buildHrPercentileLookup([{ averageHeartrate: 150 }, { averageHeartrate: 160 }])
    expect(lookup(160)).toBeNull()
  })

  it('14. rang cohérent : la FC la plus haute est au sommet', () => {
    const samples = Array.from({ length: 20 }, (_, i) => ({ averageHeartrate: 140 + i }))
    const lookup = buildHrPercentileLookup(samples)
    expect(lookup(140)).toBe(0)
    expect(lookup(159)).toBeCloseTo(1, 6)
    expect(lookup(150)!).toBeGreaterThan(0.4)
    expect(lookup(150)!).toBeLessThan(0.6)
  })

  it('15. immunisé contre une FCmax mal saisie — c’est un rang, pas un pourcentage', () => {
    // Athlète dont les footings tournent « à 88 % de FCmax » (FCmax sous-évaluée) :
    // en rang personnel, un footing reste au milieu de sa distribution.
    const footings = Array.from({ length: 30 }, () => ({ averageHeartrate: 165 }))
    const course = { averageHeartrate: 180 }
    const lookup = buildHrPercentileLookup([...footings, course])
    expect(lookup(165)!).toBeLessThan(MIN_HR_PERCENTILE)
    expect(lookup(180)!).toBeGreaterThanOrEqual(MIN_HR_PERCENTILE)
  })

  it('16. valeurs manquantes ignorées sans planter', () => {
    const lookup = buildHrPercentileLookup([
      ...Array.from({ length: 12 }, () => ({ averageHeartrate: 150 })),
      { averageHeartrate: null }, { averageHeartrate: 0 },
    ])
    expect(lookup(null)).toBeNull()
    expect(lookup(150)).not.toBeNull()
  })

  it('17. parité web ↔ mobile', () => {
    const input = { ...base, name: 'Marathon de Colmar' }
    expect(mobileDetect(input)).toEqual(detectRace(input))
  })
})
