import { describe, it, expect } from 'vitest'
import {
  detectRace,
  hasAutoGeneratedTitle,
  buildHrPercentileLookup,
  MIN_HR_PERCENTILE,
  MAX_STOP_RATIO_PCT,
  maxStopRatioPctFor,
  minHrPercentileFor,
} from '../src/lib/raceDetection'
import { detectRace as mobileDetect } from '../mobile/src/lib/raceDetection'

// Détection AUTOMATIQUE des compétitions. Presque personne ne coche « course » sur
// Strava : un athlète arrivé avec 4 ans d'historique et 427 sorties avait ZÉRO course
// étiquetée, alors que son historique contenait un marathon et deux semis. Sans
// détection, le moteur n'a aucun ancrage.
//
// PRÉCISION AVANT RAPPEL : une fausse course entre dans l'ancrage et y déplace
// durablement toutes les projections ; une course manquée ne fait que priver le moteur
// d'un point. Les cas ci-dessous sont TIRÉS DES DONNÉES RÉELLES.

const base = {
  sportType: 'Run',
  distanceM: 21100,
  movingTimeS: 5248,
  elapsedTimeS: 5274, // 0,5 % d'arrêt
  hrPercentile: 1.0,
}

describe('detectRace — vraies courses (doivent être détectées)', () => {
  it('1. « Marathon de colmar 2025 » — 41,9 km, 1,1 % d’arrêt, FC au 97e centile', () => {
    const r = detectRace({ ...base, name: 'Marathon de colmar 2025', distanceM: 41900, movingTimeS: 11294, elapsedTimeS: 11418, hrPercentile: 0.97 })
    expect(r.detected).toBe(true)
    expect(r.reasons).toContain('race_name_signal')
    expect(r.reasons).toContain('personal_intensity_high')
  })

  it('2. « Semi marathon de Mulhouse »', () => {
    expect(detectRace({ ...base, name: 'Semi marathon de Mulhouse' }).detected).toBe(true)
  })

  it('3. « Trail du muguet. 42/389 funny fun » — classement dans le nom', () => {
    const r = detectRace({ ...base, sportType: 'TrailRun', name: 'Trail du muguet. 42/389 funny fun', distanceM: 11594, movingTimeS: 4185, elapsedTimeS: 4188, hrPercentile: 0.96 })
    expect(r.detected).toBe(true)
  })

  it('4. « Trail des collines 29e au général » — placement annoncé', () => {
    const r = detectRace({ ...base, sportType: 'TrailRun', name: 'Trail des collines 29e au général, vraiment content', distanceM: 22663, movingTimeS: 7196, elapsedTimeS: 7209, hrPercentile: 0.93 })
    expect(r.detected).toBe(true)
  })
})

describe('detectRace — pièges observés (ne doivent PAS être détectés)', () => {
  it('5. « Trail dans l’après-midi » — titre AUTOMATIQUE Strava', () => {
    // Le seul vrai faux positif de la calibration : attrapé par un motif « trail d… »
    // trop laxiste. Le titre auto le rejette proprement.
    const r = detectRace({ ...base, sportType: 'TrailRun', name: "Trail dans l'après-midi" })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('auto_generated_title')
  })

  it('6. titres auto français et anglais rejetés', () => {
    for (const n of ['Course à pied le matin', 'Morning Run', 'Afternoon Trail Run', 'Trail le matin', 'Lunch Run', 'Course à pied matinale']) {
      expect(hasAutoGeneratedTitle(n), n).toBe(true)
      expect(detectRace({ ...base, name: n }).detected, n).toBe(false)
    }
  })

  it('7. séances structurées rejetées malgré une intensité de course', () => {
    for (const n of ['4x2km allure semi', 'VMA 10x400', '3x5 min tempo', 'Séance test semi', 'Fartlek 10km', 'Test de forme COROS']) {
      expect(detectRace({ ...base, name: n }).detected, n).toBe(false)
    }
  })

  it('8. sortie à titre personnalisé mais sans nom d’événement → non détectée', () => {
    // On ne confirme jamais sur la seule intensité : une sortie dominicale soutenue
    // ressemble physiologiquement à une course.
    const r = detectRace({ ...base, name: 'Il pleut comme vache qui pisse 👀' })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('no_race_name_signal')
  })

  it('9. trop d’arrêts → rejetée (une course ne s’arrête pas)', () => {
    const r = detectRace({ ...base, name: 'Marathon de Colmar', elapsedTimeS: 5248 * 1.12 })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('too_many_stops')
  })

  it('10. intensité trop basse → rejetée (« rando course » nommée comme une course)', () => {
    const r = detectRace({ ...base, name: 'Marathon de Colmar', hrPercentile: 0.4 })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('intensity_too_low')
  })

  it('11. sans signal d’intensité → JAMAIS détectée', () => {
    // Un nom seul ne suffit pas : « Marathon » peut être un footing sur le parcours.
    const r = detectRace({ ...base, name: 'Marathon de Colmar', hrPercentile: null })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('no_intensity_signal')
  })

  it('12. vélo et distances courtes écartés', () => {
    expect(detectRace({ ...base, sportType: 'Ride', name: 'Marathon de Colmar' }).detected).toBe(false)
    expect(detectRace({ ...base, name: 'Corrida de Noël', distanceM: 2000 }).detected).toBe(false)
  })
})

describe('buildHrPercentileLookup', () => {
  it('13. historique trop mince → aucun rang (donc aucune détection)', () => {
    const lookup = buildHrPercentileLookup([{ averageHeartrate: 150 }, { averageHeartrate: 160 }])
    expect(lookup(160)).toBeNull()
  })

  it('14. rang cohérent : la FC la plus haute est au sommet', () => {
    const samples = Array.from({ length: 20 }, (_, i) => ({ averageHeartrate: 140 + i }))
    const lookup = buildHrPercentileLookup(samples)
    expect(lookup(140)).toBe(0)
    expect(lookup(159)).toBeCloseTo(1, 6)
    expect(lookup(150)!).toBeGreaterThan(0.4)
    expect(lookup(150)!).toBeLessThan(0.6)
  })

  it('15. immunisé contre une FCmax mal saisie — c’est un rang, pas un pourcentage', () => {
    // Athlète dont les footings tournent « à 88 % de FCmax » (FCmax sous-évaluée) :
    // en rang personnel, un footing reste au milieu de sa distribution.
    const footings = Array.from({ length: 30 }, () => ({ averageHeartrate: 165 }))
    const course = { averageHeartrate: 180 }
    const lookup = buildHrPercentileLookup([...footings, course])
    expect(lookup(165)!).toBeLessThan(MIN_HR_PERCENTILE)
    expect(lookup(180)!).toBeGreaterThanOrEqual(MIN_HR_PERCENTILE)
  })

  it('16. valeurs manquantes ignorées sans planter', () => {
    const lookup = buildHrPercentileLookup([
      ...Array.from({ length: 12 }, () => ({ averageHeartrate: 150 })),
      { averageHeartrate: null }, { averageHeartrate: 0 },
    ])
    expect(lookup(null)).toBeNull()
    expect(lookup(150)).not.toBeNull()
  })

  it('17. parité web ↔ mobile', () => {
    const input = { ...base, name: 'Marathon de Colmar' }
    expect(mobileDetect(input)).toEqual(detectRace(input))
  })
})

// ── Formats LONGS : le détecteur était aveugle aux ultras ─────────────────────────
// Mesuré sur la base `runnerdata` le 2026-07-31 : 28 des 31 sorties de 30 km et plus
// étaient rejetées, et les 2 seules confirmées étaient deux marathons ROUTE. Les cas
// ci-dessous sont les VRAIS noms et les VRAIS temps de ces activités.
describe('detectRace — formats longs (ultras réellement présents en base)', () => {
  it('18. « Trail du GRAND BALLON » — 78,5 km / 3 914 m D+ / 12h32', () => {
    const r = detectRace({
      sportType: 'TrailRun', name: 'Trail du GRAND BALLON 🏔️🎈',
      distanceM: 78452.9, movingTimeS: 41833, elapsedTimeS: 45152, hrPercentile: 0.6,
    })
    expect(r.detected).toBe(true)
    expect(r.reasons).toContain('long_format')
  })

  it('19. « Belfortrail » — nom d’événement accolé, sans aucun autre indice', () => {
    const r = detectRace({
      sportType: 'TrailRun', name: 'Belfortrail',
      distanceM: 57289.3, movingTimeS: 38726, elapsedTimeS: 38755, hrPercentile: 0.55,
    })
    expect(r.detected).toBe(true)
  })

  it('20. « Munster trail 82 » — format annoncé dans le nom', () => {
    expect(detectRace({
      sportType: 'TrailRun', name: 'Munster trail 82 ❌',
      distanceM: 50111.4, movingTimeS: 29823, elapsedTimeS: 33316, hrPercentile: 0.6,
    }).detected).toBe(true)
  })

  it('21. les ravitaillements ne disqualifient plus un ultra (11,7 % d’arrêt sur 8h17)', () => {
    // Le même taux d’arrêt sur une course courte reste éliminatoire.
    const long = detectRace({
      sportType: 'TrailRun', name: 'Trail du petit ballon',
      distanceM: 50111.4, movingTimeS: 29823, elapsedTimeS: 33316, hrPercentile: 0.6,
    })
    const court = detectRace({
      sportType: 'TrailRun', name: 'Trail du petit ballon',
      distanceM: 11000, movingTimeS: 3600, elapsedTimeS: 4021, hrPercentile: 0.99,
    })
    expect(long.detected).toBe(true)
    expect(court.detected).toBe(false)
    expect(court.reasons).toContain('too_many_stops')
  })

  it('22. l’intensité exigée baisse avec la durée — un ultra se court en endurance', () => {
    expect(minHrPercentileFor(3600)).toBe(MIN_HR_PERCENTILE)          // 1 h : inchangé
    expect(minHrPercentileFor(5 * 3600)).toBeLessThan(MIN_HR_PERCENTILE)
    // Plancher à ZÉRO : sur un format long la FC ne porte aucune information sur le fait
    // qu'il s'agisse d'une course (un ultra se court en Z2). Le critère est inapplicable,
    // pas mal calibré — ce sont les autres portes qui assurent la précision.
    expect(minHrPercentileFor(12 * 3600)).toBe(0)
    expect(maxStopRatioPctFor(3600)).toBe(MAX_STOP_RATIO_PCT)         // 1 h : inchangé
    expect(maxStopRatioPctFor(12 * 3600)).toBeCloseTo(15, 6)          // plafond
  })

  it('23. AUCUNE régression sous 2 h : les seuils courts sont strictement inchangés', () => {
    for (const h of [0.5, 1, 1.5, 2]) {
      expect(maxStopRatioPctFor(h * 3600)).toBe(MAX_STOP_RATIO_PCT)
      expect(minHrPercentileFor(h * 3600)).toBe(MIN_HR_PERCENTILE)
    }
  })
})

// Le vocabulaire trail ouvre une porte : il faut donc refermer celle des SORTIES.
// Sans ce garde-fou, toute sortie longue en montagne deviendrait une compétition —
// et une fausse course pollue durablement l’ancrage.
describe('detectRace — une sortie longue en montagne n’est PAS une course', () => {
  const longRun = { sportType: 'TrailRun', distanceM: 33674.8, movingTimeS: 22591, elapsedTimeS: 24003, hrPercentile: 0.9 }

  it('24. « Sortie trail », « Sorti trail avec Max », « Sortie grand ballon » écartées', () => {
    for (const name of ['Sortie trail', 'Sorti trail avec Max il ma mit dans le mal', 'Sortie grand ballon petit ballon MOR', '🐗Sortie choc pour le ptit ballon dans 1 mois']) {
      const r = detectRace({ ...longRun, name })
      expect(r.detected, name).toBe(false)
      expect(r.reasons, name).toContain('looks_like_workout')
    }
  })

  it('25. « Trail By juju » — un trail entre copains n’est pas un événement', () => {
    expect(detectRace({ ...longRun, name: 'Trail By juju' }).detected).toBe(false)
  })

  it('26. « Randonnée trail » et « Rando course » restent des séances', () => {
    expect(detectRace({ ...longRun, name: 'Randonnée trail juste 😍' }).detected).toBe(false)
    expect(detectRace({ ...longRun, name: 'Rando course 6h45' }).detected).toBe(false)
  })

  it('27. parité web ↔ mobile sur un format long', () => {
    const input = { ...longRun, name: 'Trail du GRAND BALLON', movingTimeS: 41833, elapsedTimeS: 45152 }
    expect(mobileDetect(input)).toEqual(detectRace(input))
  })
})

// Cas RÉEL qui a motivé le plancher d'intensité à zéro sur les formats longs.
describe('detectRace — un ultra couru en Z2 (cas Grand Ballon)', () => {
  const grandBallon = {
    sportType: 'TrailRun' as const,
    name: 'Trail du GRAND BALLON 🏔️🎈',
    distanceM: 78452.9,
    movingTimeS: 41833,
    elapsedTimeS: 45152,
  }

  it('33. détecté malgré une FC moyenne SOUS la médiane de son auteur', () => {
    // 135,8 bpm sur 12h32 : rang personnel bas, ce qui est NORMAL sur un ultra.
    const r = detectRace({ ...grandBallon, hrPercentile: 0.2 })
    expect(r.detected).toBe(true)
    expect(r.reasons).toContain('long_format')
  })

  it('34. mais une SORTIE longue de même profil reste exclue', () => {
    // Même durée, même FC : seul le nom change. La précision vient des autres portes.
    expect(detectRace({ ...grandBallon, name: 'Sortie trail grand ballon', hrPercentile: 0.2 }).detected).toBe(false)
    expect(detectRace({ ...grandBallon, name: 'Rando course 12h', hrPercentile: 0.2 }).detected).toBe(false)
  })

  it('35. et une course COURTE à FC basse reste exclue (seuil intact sous 2 h)', () => {
    const r = detectRace({ ...grandBallon, distanceM: 11000, movingTimeS: 3600, elapsedTimeS: 3620, hrPercentile: 0.2 })
    expect(r.detected).toBe(false)
    expect(r.reasons).toContain('intensity_too_low')
  })
})
