create table if not exists public.garmin_connections (
  user_id uuid primary key references auth.users(id) on delete cascade,
  garmin_user_id text,
  access_token text,
  refresh_token text,
  token_type text,
  scope text,
  expires_at timestamptz,
  connected_at timestamptz,
  last_sync_at timestamptz,
  revoked_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists garmin_connections_garmin_user_id_uidx
  on public.garmin_connections(garmin_user_id)
  where garmin_user_id is not null;

alter table public.garmin_connections enable row level security;
revoke all on public.garmin_connections from anon, authenticated;

create table if not exists public.garmin_activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  garmin_activity_id text not null,
  activity_type text,
  activity_name text,
  start_time timestamptz,
  duration_seconds integer,
  distance_meters double precision,
  elevation_gain_meters double precision,
  average_heart_rate double precision,
  max_heart_rate double precision,
  average_cadence double precision,
  calories double precision,
  raw_data jsonb not null default '{}'::jsonb,
  source_updated_at timestamptz,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, garmin_activity_id)
);

alter table public.garmin_activities enable row level security;
create policy "garmin_activities_select_own"
  on public.garmin_activities for select
  to authenticated
  using ((select auth.uid()) = user_id);

create table if not exists public.garmin_health_daily (
  user_id uuid not null references auth.users(id) on delete cascade,
  calendar_date date not null,
  daily jsonb,
  sleep jsonb,
  stress jsonb,
  hrv jsonb,
  body_battery jsonb,
  body_composition jsonb,
  raw_data jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, calendar_date)
);

alter table public.garmin_health_daily enable row level security;
create policy "garmin_health_daily_select_own"
  on public.garmin_health_daily for select
  to authenticated
  using ((select auth.uid()) = user_id);

create table if not exists public.garmin_webhook_events (
  id bigint generated by default as identity primary key,
  event_key text,
  event_type text,
  garmin_user_id text,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text
);

create unique index if not exists garmin_webhook_events_event_key_uidx
  on public.garmin_webhook_events(event_key)
  where event_key is not null;

alter table public.garmin_webhook_events enable row level security;
revoke all on public.garmin_webhook_events from anon, authenticated;

create index if not exists garmin_activities_user_start_idx
  on public.garmin_activities(user_id, start_time desc);
create index if not exists garmin_health_daily_user_date_idx
  on public.garmin_health_daily(user_id, calendar_date desc);
create index if not exists garmin_webhook_events_received_idx
  on public.garmin_webhook_events(received_at desc);
